[package]
name = "patchkeeper"
version = "0.1.0"
authors = ["Per Liden <per@malloc.se>"]
edition = "2024"

[[bin]]
name = "pk"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
colored = "3.0"
ratatui = "0.29"
crossterm = "0.29"
itertools = "0.14"
immargs = "0.1"
git2 = { version = "0.20", features = ["ssh", "vendored-libgit2"] }

[patch.crates-io]
git2 = { git = 'https://github.com/pliden/git2-rs.git' }
